set(_CATKIN_CURRENT_PACKAGE "thinkrob_pendant")
set(thinkrob_pendant_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(thinkrob_pendant_DEPRECATED "")
set(thinkrob_pendant_VERSION "0.2.8")
set(thinkrob_pendant_BUILD_DEPENDS "message_generation" "qt_build" "roscpp" "std_msgs" "libqt4-dev")
set(thinkrob_pendant_RUN_DEPENDS "message_runtime" "qt_build" "roscpp" "std_msgs" "libqt4-dev")
set(thinkrob_pendant_BUILDTOOL_DEPENDS "catkin")