/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/zhangjian/qt_environment/qt_programmer/pendant/qt_ros_zhangjian/src/thinkrob_pendant/srv/TwoInts.srv
 *
 */


#ifndef THINKROB_PENDANT_MESSAGE_TWOINTS_H
#define THINKROB_PENDANT_MESSAGE_TWOINTS_H

#include <ros/service_traits.h>


#include <thinkrob_pendant/TwoIntsRequest.h>
#include <thinkrob_pendant/TwoIntsResponse.h>


namespace thinkrob_pendant
{

struct TwoInts
{

typedef TwoIntsRequest Request;
typedef TwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TwoInts
} // namespace thinkrob_pendant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::thinkrob_pendant::TwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::thinkrob_pendant::TwoInts&) { return value(); }
};

template<>
struct DataType< ::thinkrob_pendant::TwoInts > {
  static const char* value()
  {
    return "thinkrob_pendant/TwoInts";
  }

  static const char* value(const ::thinkrob_pendant::TwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::thinkrob_pendant::TwoIntsRequest> should match 
// service_traits::MD5Sum< ::thinkrob_pendant::TwoInts > 
template<>
struct MD5Sum< ::thinkrob_pendant::TwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::thinkrob_pendant::TwoInts >::value();
  }
  static const char* value(const ::thinkrob_pendant::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::thinkrob_pendant::TwoIntsRequest> should match 
// service_traits::DataType< ::thinkrob_pendant::TwoInts > 
template<>
struct DataType< ::thinkrob_pendant::TwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::thinkrob_pendant::TwoInts >::value();
  }
  static const char* value(const ::thinkrob_pendant::TwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::thinkrob_pendant::TwoIntsResponse> should match 
// service_traits::MD5Sum< ::thinkrob_pendant::TwoInts > 
template<>
struct MD5Sum< ::thinkrob_pendant::TwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::thinkrob_pendant::TwoInts >::value();
  }
  static const char* value(const ::thinkrob_pendant::TwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::thinkrob_pendant::TwoIntsResponse> should match 
// service_traits::DataType< ::thinkrob_pendant::TwoInts > 
template<>
struct DataType< ::thinkrob_pendant::TwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::thinkrob_pendant::TwoInts >::value();
  }
  static const char* value(const ::thinkrob_pendant::TwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THINKROB_PENDANT_MESSAGE_TWOINTS_H
