/********************************************************************************
** Form generated from reading UI file 'main_window.ui'
**
** Created: Fri Feb 19 10:29:56 2016
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAIN_WINDOW_H
#define UI_MAIN_WINDOW_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QStackedWidget>
#include <QtGui/QTableWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindowDesign
{
public:
    QAction *action_Quit;
    QAction *action_Preferences;
    QAction *actionAbout;
    QAction *actionAbout_Qt;
    QWidget *centralwidget;
    QWidget *widget;
    QTextEdit *J2_value_2;
    QTextEdit *J5_value_2;
    QTextEdit *J6_value;
    QLabel *J5_name_2;
    QLabel *J6_name_2;
    QLabel *J6_name;
    QLabel *J3_name;
    QLabel *J4_name_2;
    QLabel *J4_name;
    QLabel *J1_name;
    QTextEdit *J3_value;
    QTextEdit *J1_value_2;
    QLabel *joint_coordinate_table;
    QLabel *J2_name;
    QLabel *J2_name_2;
    QLabel *J1_X;
    QLabel *Rectangular_coordinate_table;
    QTextEdit *J2_value;
    QTextEdit *J1_value;
    QTextEdit *J5_value;
    QTextEdit *J6_value_2;
    QTextEdit *J4_value_2;
    QTextEdit *J4_value;
    QTextEdit *J3_value_2;
    QLabel *J3_name_2;
    QLabel *J5_name;
    QStackedWidget *main_interface;
    QWidget *parameter_set_page;
    QPushButton *zero_setting;
    QPushButton *administrators_login;
    QPushButton *administrators_quit;
    QPushButton *administrators_modify_passwd;
    QPushButton *user_login;
    QPushButton *user_quit;
    QPushButton *user_modify_passwd;
    QLabel *label_3;
    QLabel *label_4;
    QWidget *point_to_point_page;
    QWidget *teacher_area;
    QPushButton *joint_coorinate_button;
    QPushButton *world_coorinate_button;
    QPushButton *tool_coorinate_button;
    QPushButton *workpiece_coordinate_button;
    QPushButton *J1_negative_direction;
    QLabel *J3_teacher_label;
    QLabel *J2_teach_label;
    QLabel *J1_teach_label;
    QLabel *J5_teach_label;
    QLabel *J4_teach_label;
    QLabel *J6_teach_label;
    QPushButton *J1_positive_direction;
    QPushButton *J2_positive_direction;
    QPushButton *J2_negative_direction;
    QPushButton *J3_positive_direction;
    QPushButton *J4_positive_direction;
    QPushButton *J5_positive_direction;
    QPushButton *J6_positive_direction;
    QPushButton *J3_negative_direction;
    QPushButton *J4_negative_direction;
    QPushButton *J5_negative_direction;
    QPushButton *J6_negative_direction;
    QPushButton *new_point;
    QPushButton *modify_point;
    QPushButton *delete_point;
    QPushButton *save_point;
    QPushButton *stop_point_motion;
    QPushButton *point_to_point_motion;
    QPushButton *straight_line_motion;
    QTableWidget *teacher_point_tableWidget;
    QLabel *label_2;
    QTextEdit *teacher_speed_edittext;
    QWidget *programmer_design_page;
    QTableWidget *programmer_design_display;
    QWidget *operation;
    QPushButton *insert_button;
    QPushButton *delete_button;
    QPushButton *save_button;
    QPushButton *save_as_button;
    QPushButton *new_file_button;
    QPushButton *open_button;
    QPushButton *common_function_instruction;
    QPushButton *sport_control_instruction;
    QPushButton *extended_instruction;
    QWidget *run_programmer_page;
    QTableWidget *run_programmer_content;
    QWidget *widget_3;
    QPushButton *run_speed_set_button;
    QPushButton *stop_programmer_button;
    QPushButton *pause_programmer_button;
    QPushButton *run_button;
    QPushButton *cycle_switch_button;
    QLabel *label;
    QTextEdit *run_position;
    QWidget *page_3;
    QWidget *widget_2;
    QPushButton *run_programmer;
    QPushButton *point_teacher;
    QPushButton *programmer_design;
    QPushButton *parameter_setting;

    void setupUi(QMainWindow *MainWindowDesign)
    {
        if (MainWindowDesign->objectName().isEmpty())
            MainWindowDesign->setObjectName(QString::fromUtf8("MainWindowDesign"));
        MainWindowDesign->setEnabled(true);
        MainWindowDesign->resize(1024, 768);
        MainWindowDesign->setLocale(QLocale(QLocale::English, QLocale::Australia));
        action_Quit = new QAction(MainWindowDesign);
        action_Quit->setObjectName(QString::fromUtf8("action_Quit"));
        action_Quit->setShortcutContext(Qt::ApplicationShortcut);
        action_Preferences = new QAction(MainWindowDesign);
        action_Preferences->setObjectName(QString::fromUtf8("action_Preferences"));
        actionAbout = new QAction(MainWindowDesign);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionAbout_Qt = new QAction(MainWindowDesign);
        actionAbout_Qt->setObjectName(QString::fromUtf8("actionAbout_Qt"));
        centralwidget = new QWidget(MainWindowDesign);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        widget = new QWidget(centralwidget);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(760, 0, 261, 391));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(widget->sizePolicy().hasHeightForWidth());
        widget->setSizePolicy(sizePolicy);
        J2_value_2 = new QTextEdit(widget);
        J2_value_2->setObjectName(QString::fromUtf8("J2_value_2"));
        J2_value_2->setGeometry(QRect(34, 320, 91, 31));
        J2_value_2->setTextInteractionFlags(Qt::NoTextInteraction);
        J5_value_2 = new QTextEdit(widget);
        J5_value_2->setObjectName(QString::fromUtf8("J5_value_2"));
        J5_value_2->setGeometry(QRect(168, 320, 91, 31));
        J5_value_2->setTextInteractionFlags(Qt::NoTextInteraction);
        J6_value = new QTextEdit(widget);
        J6_value->setObjectName(QString::fromUtf8("J6_value"));
        J6_value->setGeometry(QRect(168, 140, 91, 31));
        J6_value->setTextInteractionFlags(Qt::NoTextInteraction);
        J5_name_2 = new QLabel(widget);
        J5_name_2->setObjectName(QString::fromUtf8("J5_name_2"));
        J5_name_2->setGeometry(QRect(137, 325, 30, 21));
        QFont font;
        font.setPointSize(16);
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        font.setKerning(true);
        J5_name_2->setFont(font);
        J5_name_2->setContextMenuPolicy(Qt::CustomContextMenu);
        J5_name_2->setTextFormat(Qt::AutoText);
        J5_name_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J5_name_2->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J6_name_2 = new QLabel(widget);
        J6_name_2->setObjectName(QString::fromUtf8("J6_name_2"));
        J6_name_2->setGeometry(QRect(137, 365, 30, 21));
        J6_name_2->setFont(font);
        J6_name_2->setContextMenuPolicy(Qt::CustomContextMenu);
        J6_name_2->setTextFormat(Qt::AutoText);
        J6_name_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J6_name_2->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J6_name = new QLabel(widget);
        J6_name->setObjectName(QString::fromUtf8("J6_name"));
        J6_name->setGeometry(QRect(137, 145, 25, 21));
        J6_name->setFont(font);
        J6_name->setContextMenuPolicy(Qt::CustomContextMenu);
        J6_name->setTextFormat(Qt::AutoText);
        J6_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J6_name->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J3_name = new QLabel(widget);
        J3_name->setObjectName(QString::fromUtf8("J3_name"));
        J3_name->setGeometry(QRect(10, 145, 25, 21));
        J3_name->setFont(font);
        J3_name->setContextMenuPolicy(Qt::CustomContextMenu);
        J3_name->setTextFormat(Qt::AutoText);
        J3_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J3_name->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J4_name_2 = new QLabel(widget);
        J4_name_2->setObjectName(QString::fromUtf8("J4_name_2"));
        J4_name_2->setGeometry(QRect(137, 285, 30, 21));
        J4_name_2->setFont(font);
        J4_name_2->setContextMenuPolicy(Qt::CustomContextMenu);
        J4_name_2->setTextFormat(Qt::AutoText);
        J4_name_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J4_name_2->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J4_name = new QLabel(widget);
        J4_name->setObjectName(QString::fromUtf8("J4_name"));
        J4_name->setGeometry(QRect(137, 65, 25, 21));
        J4_name->setFont(font);
        J4_name->setContextMenuPolicy(Qt::CustomContextMenu);
        J4_name->setTextFormat(Qt::AutoText);
        J4_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J4_name->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J1_name = new QLabel(widget);
        J1_name->setObjectName(QString::fromUtf8("J1_name"));
        J1_name->setGeometry(QRect(10, 65, 25, 21));
        J1_name->setFont(font);
        J1_name->setContextMenuPolicy(Qt::CustomContextMenu);
        J1_name->setTextFormat(Qt::AutoText);
        J1_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J1_name->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J3_value = new QTextEdit(widget);
        J3_value->setObjectName(QString::fromUtf8("J3_value"));
        J3_value->setGeometry(QRect(34, 140, 91, 31));
        J3_value->setTextInteractionFlags(Qt::NoTextInteraction);
        J1_value_2 = new QTextEdit(widget);
        J1_value_2->setObjectName(QString::fromUtf8("J1_value_2"));
        J1_value_2->setGeometry(QRect(34, 280, 91, 31));
        J1_value_2->setTextInteractionFlags(Qt::NoTextInteraction);
        joint_coordinate_table = new QLabel(widget);
        joint_coordinate_table->setObjectName(QString::fromUtf8("joint_coordinate_table"));
        joint_coordinate_table->setGeometry(QRect(31, 8, 211, 51));
        QFont font1;
        font1.setPointSize(28);
        font1.setBold(true);
        font1.setItalic(false);
        font1.setWeight(75);
        font1.setKerning(true);
        joint_coordinate_table->setFont(font1);
        joint_coordinate_table->setContextMenuPolicy(Qt::CustomContextMenu);
        joint_coordinate_table->setTextFormat(Qt::AutoText);
        joint_coordinate_table->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        joint_coordinate_table->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J2_name = new QLabel(widget);
        J2_name->setObjectName(QString::fromUtf8("J2_name"));
        J2_name->setGeometry(QRect(10, 105, 31, 20));
        J2_name->setFont(font);
        J2_name->setContextMenuPolicy(Qt::CustomContextMenu);
        J2_name->setTextFormat(Qt::AutoText);
        J2_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J2_name->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J2_name_2 = new QLabel(widget);
        J2_name_2->setObjectName(QString::fromUtf8("J2_name_2"));
        J2_name_2->setGeometry(QRect(10, 325, 31, 20));
        J2_name_2->setFont(font);
        J2_name_2->setContextMenuPolicy(Qt::CustomContextMenu);
        J2_name_2->setTextFormat(Qt::AutoText);
        J2_name_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J2_name_2->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J1_X = new QLabel(widget);
        J1_X->setObjectName(QString::fromUtf8("J1_X"));
        J1_X->setGeometry(QRect(10, 285, 25, 21));
        J1_X->setFont(font);
        J1_X->setContextMenuPolicy(Qt::CustomContextMenu);
        J1_X->setTextFormat(Qt::AutoText);
        J1_X->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J1_X->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        Rectangular_coordinate_table = new QLabel(widget);
        Rectangular_coordinate_table->setObjectName(QString::fromUtf8("Rectangular_coordinate_table"));
        Rectangular_coordinate_table->setGeometry(QRect(31, 215, 211, 51));
        Rectangular_coordinate_table->setFont(font1);
        Rectangular_coordinate_table->setContextMenuPolicy(Qt::CustomContextMenu);
        Rectangular_coordinate_table->setTextFormat(Qt::AutoText);
        Rectangular_coordinate_table->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        Rectangular_coordinate_table->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J2_value = new QTextEdit(widget);
        J2_value->setObjectName(QString::fromUtf8("J2_value"));
        J2_value->setGeometry(QRect(34, 100, 91, 31));
        J2_value->setTextInteractionFlags(Qt::NoTextInteraction);
        J1_value = new QTextEdit(widget);
        J1_value->setObjectName(QString::fromUtf8("J1_value"));
        J1_value->setGeometry(QRect(34, 60, 91, 31));
        J1_value->setTextInteractionFlags(Qt::NoTextInteraction);
        J5_value = new QTextEdit(widget);
        J5_value->setObjectName(QString::fromUtf8("J5_value"));
        J5_value->setGeometry(QRect(168, 100, 91, 31));
        J5_value->setTextInteractionFlags(Qt::NoTextInteraction);
        J6_value_2 = new QTextEdit(widget);
        J6_value_2->setObjectName(QString::fromUtf8("J6_value_2"));
        J6_value_2->setGeometry(QRect(168, 360, 91, 31));
        J6_value_2->setTextInteractionFlags(Qt::NoTextInteraction);
        J4_value_2 = new QTextEdit(widget);
        J4_value_2->setObjectName(QString::fromUtf8("J4_value_2"));
        J4_value_2->setGeometry(QRect(168, 280, 91, 31));
        J4_value_2->setTextInteractionFlags(Qt::NoTextInteraction);
        J4_value = new QTextEdit(widget);
        J4_value->setObjectName(QString::fromUtf8("J4_value"));
        J4_value->setGeometry(QRect(168, 60, 91, 31));
        J4_value->setTextInteractionFlags(Qt::NoTextInteraction);
        J3_value_2 = new QTextEdit(widget);
        J3_value_2->setObjectName(QString::fromUtf8("J3_value_2"));
        J3_value_2->setGeometry(QRect(34, 360, 91, 31));
        J3_value_2->setTextInteractionFlags(Qt::NoTextInteraction);
        J3_name_2 = new QLabel(widget);
        J3_name_2->setObjectName(QString::fromUtf8("J3_name_2"));
        J3_name_2->setGeometry(QRect(10, 365, 25, 21));
        J3_name_2->setFont(font);
        J3_name_2->setContextMenuPolicy(Qt::CustomContextMenu);
        J3_name_2->setTextFormat(Qt::AutoText);
        J3_name_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J3_name_2->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J5_name = new QLabel(widget);
        J5_name->setObjectName(QString::fromUtf8("J5_name"));
        J5_name->setGeometry(QRect(137, 105, 25, 21));
        J5_name->setFont(font);
        J5_name->setContextMenuPolicy(Qt::CustomContextMenu);
        J5_name->setTextFormat(Qt::AutoText);
        J5_name->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J5_name->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        main_interface = new QStackedWidget(centralwidget);
        main_interface->setObjectName(QString::fromUtf8("main_interface"));
        main_interface->setGeometry(QRect(0, 0, 751, 611));
        parameter_set_page = new QWidget();
        parameter_set_page->setObjectName(QString::fromUtf8("parameter_set_page"));
        zero_setting = new QPushButton(parameter_set_page);
        zero_setting->setObjectName(QString::fromUtf8("zero_setting"));
        zero_setting->setGeometry(QRect(90, 410, 80, 40));
        administrators_login = new QPushButton(parameter_set_page);
        administrators_login->setObjectName(QString::fromUtf8("administrators_login"));
        administrators_login->setGeometry(QRect(90, 220, 80, 40));
        administrators_quit = new QPushButton(parameter_set_page);
        administrators_quit->setObjectName(QString::fromUtf8("administrators_quit"));
        administrators_quit->setGeometry(QRect(270, 220, 80, 40));
        administrators_modify_passwd = new QPushButton(parameter_set_page);
        administrators_modify_passwd->setObjectName(QString::fromUtf8("administrators_modify_passwd"));
        administrators_modify_passwd->setGeometry(QRect(450, 220, 80, 40));
        user_login = new QPushButton(parameter_set_page);
        user_login->setObjectName(QString::fromUtf8("user_login"));
        user_login->setGeometry(QRect(90, 115, 80, 40));
        user_quit = new QPushButton(parameter_set_page);
        user_quit->setObjectName(QString::fromUtf8("user_quit"));
        user_quit->setGeometry(QRect(270, 115, 80, 40));
        user_modify_passwd = new QPushButton(parameter_set_page);
        user_modify_passwd->setObjectName(QString::fromUtf8("user_modify_passwd"));
        user_modify_passwd->setGeometry(QRect(450, 115, 80, 40));
        label_3 = new QLabel(parameter_set_page);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(20, 190, 101, 17));
        label_4 = new QLabel(parameter_set_page);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 85, 101, 17));
        main_interface->addWidget(parameter_set_page);
        point_to_point_page = new QWidget();
        point_to_point_page->setObjectName(QString::fromUtf8("point_to_point_page"));
        teacher_area = new QWidget(point_to_point_page);
        teacher_area->setObjectName(QString::fromUtf8("teacher_area"));
        teacher_area->setGeometry(QRect(600, 0, 150, 611));
        joint_coorinate_button = new QPushButton(teacher_area);
        joint_coorinate_button->setObjectName(QString::fromUtf8("joint_coorinate_button"));
        joint_coorinate_button->setGeometry(QRect(30, 25, 90, 40));
        world_coorinate_button = new QPushButton(teacher_area);
        world_coorinate_button->setObjectName(QString::fromUtf8("world_coorinate_button"));
        world_coorinate_button->setGeometry(QRect(30, 70, 90, 40));
        tool_coorinate_button = new QPushButton(teacher_area);
        tool_coorinate_button->setObjectName(QString::fromUtf8("tool_coorinate_button"));
        tool_coorinate_button->setGeometry(QRect(30, 115, 90, 40));
        workpiece_coordinate_button = new QPushButton(teacher_area);
        workpiece_coordinate_button->setObjectName(QString::fromUtf8("workpiece_coordinate_button"));
        workpiece_coordinate_button->setGeometry(QRect(30, 160, 90, 40));
        J1_negative_direction = new QPushButton(teacher_area);
        J1_negative_direction->setObjectName(QString::fromUtf8("J1_negative_direction"));
        J1_negative_direction->setGeometry(QRect(6, 230, 55, 55));
        J3_teacher_label = new QLabel(teacher_area);
        J3_teacher_label->setObjectName(QString::fromUtf8("J3_teacher_label"));
        J3_teacher_label->setGeometry(QRect(63, 368, 25, 21));
        J3_teacher_label->setFont(font);
        J3_teacher_label->setContextMenuPolicy(Qt::CustomContextMenu);
        J3_teacher_label->setTextFormat(Qt::AutoText);
        J3_teacher_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J3_teacher_label->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J2_teach_label = new QLabel(teacher_area);
        J2_teach_label->setObjectName(QString::fromUtf8("J2_teach_label"));
        J2_teach_label->setGeometry(QRect(63, 309, 31, 20));
        J2_teach_label->setFont(font);
        J2_teach_label->setContextMenuPolicy(Qt::CustomContextMenu);
        J2_teach_label->setTextFormat(Qt::AutoText);
        J2_teach_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J2_teach_label->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J1_teach_label = new QLabel(teacher_area);
        J1_teach_label->setObjectName(QString::fromUtf8("J1_teach_label"));
        J1_teach_label->setGeometry(QRect(63, 247, 25, 21));
        J1_teach_label->setFont(font);
        J1_teach_label->setContextMenuPolicy(Qt::CustomContextMenu);
        J1_teach_label->setTextFormat(Qt::AutoText);
        J1_teach_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J1_teach_label->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J5_teach_label = new QLabel(teacher_area);
        J5_teach_label->setObjectName(QString::fromUtf8("J5_teach_label"));
        J5_teach_label->setGeometry(QRect(63, 489, 25, 21));
        J5_teach_label->setFont(font);
        J5_teach_label->setContextMenuPolicy(Qt::CustomContextMenu);
        J5_teach_label->setTextFormat(Qt::AutoText);
        J5_teach_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J5_teach_label->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J4_teach_label = new QLabel(teacher_area);
        J4_teach_label->setObjectName(QString::fromUtf8("J4_teach_label"));
        J4_teach_label->setGeometry(QRect(63, 427, 25, 21));
        J4_teach_label->setFont(font);
        J4_teach_label->setContextMenuPolicy(Qt::CustomContextMenu);
        J4_teach_label->setTextFormat(Qt::AutoText);
        J4_teach_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J4_teach_label->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J6_teach_label = new QLabel(teacher_area);
        J6_teach_label->setObjectName(QString::fromUtf8("J6_teach_label"));
        J6_teach_label->setGeometry(QRect(62, 548, 25, 21));
        J6_teach_label->setFont(font);
        J6_teach_label->setContextMenuPolicy(Qt::CustomContextMenu);
        J6_teach_label->setTextFormat(Qt::AutoText);
        J6_teach_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        J6_teach_label->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        J1_positive_direction = new QPushButton(teacher_area);
        J1_positive_direction->setObjectName(QString::fromUtf8("J1_positive_direction"));
        J1_positive_direction->setGeometry(QRect(90, 230, 55, 55));
        J2_positive_direction = new QPushButton(teacher_area);
        J2_positive_direction->setObjectName(QString::fromUtf8("J2_positive_direction"));
        J2_positive_direction->setGeometry(QRect(90, 290, 55, 55));
        J2_negative_direction = new QPushButton(teacher_area);
        J2_negative_direction->setObjectName(QString::fromUtf8("J2_negative_direction"));
        J2_negative_direction->setGeometry(QRect(6, 290, 55, 55));
        J3_positive_direction = new QPushButton(teacher_area);
        J3_positive_direction->setObjectName(QString::fromUtf8("J3_positive_direction"));
        J3_positive_direction->setGeometry(QRect(90, 350, 55, 55));
        J4_positive_direction = new QPushButton(teacher_area);
        J4_positive_direction->setObjectName(QString::fromUtf8("J4_positive_direction"));
        J4_positive_direction->setGeometry(QRect(90, 410, 55, 55));
        J5_positive_direction = new QPushButton(teacher_area);
        J5_positive_direction->setObjectName(QString::fromUtf8("J5_positive_direction"));
        J5_positive_direction->setGeometry(QRect(90, 470, 55, 55));
        J6_positive_direction = new QPushButton(teacher_area);
        J6_positive_direction->setObjectName(QString::fromUtf8("J6_positive_direction"));
        J6_positive_direction->setGeometry(QRect(90, 530, 55, 55));
        J3_negative_direction = new QPushButton(teacher_area);
        J3_negative_direction->setObjectName(QString::fromUtf8("J3_negative_direction"));
        J3_negative_direction->setGeometry(QRect(6, 350, 55, 55));
        J4_negative_direction = new QPushButton(teacher_area);
        J4_negative_direction->setObjectName(QString::fromUtf8("J4_negative_direction"));
        J4_negative_direction->setGeometry(QRect(6, 410, 55, 55));
        J5_negative_direction = new QPushButton(teacher_area);
        J5_negative_direction->setObjectName(QString::fromUtf8("J5_negative_direction"));
        J5_negative_direction->setGeometry(QRect(6, 470, 55, 55));
        J6_negative_direction = new QPushButton(teacher_area);
        J6_negative_direction->setObjectName(QString::fromUtf8("J6_negative_direction"));
        J6_negative_direction->setGeometry(QRect(6, 530, 55, 55));
        new_point = new QPushButton(point_to_point_page);
        new_point->setObjectName(QString::fromUtf8("new_point"));
        new_point->setGeometry(QRect(120, 420, 90, 40));
        modify_point = new QPushButton(point_to_point_page);
        modify_point->setObjectName(QString::fromUtf8("modify_point"));
        modify_point->setGeometry(QRect(240, 370, 90, 40));
        delete_point = new QPushButton(point_to_point_page);
        delete_point->setObjectName(QString::fromUtf8("delete_point"));
        delete_point->setGeometry(QRect(355, 370, 90, 40));
        save_point = new QPushButton(point_to_point_page);
        save_point->setObjectName(QString::fromUtf8("save_point"));
        save_point->setGeometry(QRect(470, 370, 90, 40));
        stop_point_motion = new QPushButton(point_to_point_page);
        stop_point_motion->setObjectName(QString::fromUtf8("stop_point_motion"));
        stop_point_motion->setGeometry(QRect(240, 420, 90, 40));
        point_to_point_motion = new QPushButton(point_to_point_page);
        point_to_point_motion->setObjectName(QString::fromUtf8("point_to_point_motion"));
        point_to_point_motion->setGeometry(QRect(355, 420, 90, 40));
        straight_line_motion = new QPushButton(point_to_point_page);
        straight_line_motion->setObjectName(QString::fromUtf8("straight_line_motion"));
        straight_line_motion->setGeometry(QRect(470, 421, 90, 40));
        teacher_point_tableWidget = new QTableWidget(point_to_point_page);
        teacher_point_tableWidget->setObjectName(QString::fromUtf8("teacher_point_tableWidget"));
        teacher_point_tableWidget->setGeometry(QRect(6, 4, 581, 351));
        teacher_point_tableWidget->setWordWrap(false);
        teacher_point_tableWidget->setRowCount(0);
        teacher_point_tableWidget->horizontalHeader()->setVisible(false);
        teacher_point_tableWidget->horizontalHeader()->setCascadingSectionResizes(false);
        teacher_point_tableWidget->horizontalHeader()->setDefaultSectionSize(100);
        teacher_point_tableWidget->horizontalHeader()->setHighlightSections(true);
        teacher_point_tableWidget->horizontalHeader()->setMinimumSectionSize(0);
        teacher_point_tableWidget->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        label_2 = new QLabel(point_to_point_page);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(46, 382, 66, 17));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(false);
        font2.setItalic(false);
        font2.setWeight(50);
        label_2->setFont(font2);
        teacher_speed_edittext = new QTextEdit(point_to_point_page);
        teacher_speed_edittext->setObjectName(QString::fromUtf8("teacher_speed_edittext"));
        teacher_speed_edittext->setGeometry(QRect(120, 370, 90, 40));
        teacher_speed_edittext->setReadOnly(false);
        teacher_speed_edittext->setTextInteractionFlags(Qt::TextEditorInteraction);
        main_interface->addWidget(point_to_point_page);
        programmer_design_page = new QWidget();
        programmer_design_page->setObjectName(QString::fromUtf8("programmer_design_page"));
        programmer_design_display = new QTableWidget(programmer_design_page);
        programmer_design_display->setObjectName(QString::fromUtf8("programmer_design_display"));
        programmer_design_display->setGeometry(QRect(136, 20, 561, 331));
        programmer_design_display->setWordWrap(false);
        programmer_design_display->setRowCount(0);
        programmer_design_display->horizontalHeader()->setVisible(false);
        programmer_design_display->horizontalHeader()->setCascadingSectionResizes(false);
        programmer_design_display->horizontalHeader()->setDefaultSectionSize(100);
        programmer_design_display->horizontalHeader()->setHighlightSections(true);
        programmer_design_display->horizontalHeader()->setMinimumSectionSize(0);
        programmer_design_display->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        operation = new QWidget(programmer_design_page);
        operation->setObjectName(QString::fromUtf8("operation"));
        operation->setGeometry(QRect(160, 360, 501, 61));
        insert_button = new QPushButton(operation);
        insert_button->setObjectName(QString::fromUtf8("insert_button"));
        insert_button->setGeometry(QRect(20, 13, 70, 35));
        delete_button = new QPushButton(operation);
        delete_button->setObjectName(QString::fromUtf8("delete_button"));
        delete_button->setGeometry(QRect(100, 13, 70, 35));
        save_button = new QPushButton(operation);
        save_button->setObjectName(QString::fromUtf8("save_button"));
        save_button->setGeometry(QRect(180, 13, 70, 35));
        save_as_button = new QPushButton(operation);
        save_as_button->setObjectName(QString::fromUtf8("save_as_button"));
        save_as_button->setGeometry(QRect(260, 13, 70, 35));
        new_file_button = new QPushButton(operation);
        new_file_button->setObjectName(QString::fromUtf8("new_file_button"));
        new_file_button->setGeometry(QRect(340, 13, 70, 35));
        open_button = new QPushButton(operation);
        open_button->setObjectName(QString::fromUtf8("open_button"));
        open_button->setGeometry(QRect(420, 13, 70, 35));
        common_function_instruction = new QPushButton(programmer_design_page);
        common_function_instruction->setObjectName(QString::fromUtf8("common_function_instruction"));
        common_function_instruction->setGeometry(QRect(10, 40, 121, 41));
        sport_control_instruction = new QPushButton(programmer_design_page);
        sport_control_instruction->setObjectName(QString::fromUtf8("sport_control_instruction"));
        sport_control_instruction->setGeometry(QRect(10, 100, 121, 41));
        extended_instruction = new QPushButton(programmer_design_page);
        extended_instruction->setObjectName(QString::fromUtf8("extended_instruction"));
        extended_instruction->setGeometry(QRect(10, 160, 121, 41));
        main_interface->addWidget(programmer_design_page);
        run_programmer_page = new QWidget();
        run_programmer_page->setObjectName(QString::fromUtf8("run_programmer_page"));
        run_programmer_content = new QTableWidget(run_programmer_page);
        run_programmer_content->setObjectName(QString::fromUtf8("run_programmer_content"));
        run_programmer_content->setEnabled(true);
        run_programmer_content->setGeometry(QRect(10, 50, 621, 411));
        run_programmer_content->setWordWrap(false);
        run_programmer_content->setRowCount(0);
        run_programmer_content->horizontalHeader()->setVisible(false);
        run_programmer_content->horizontalHeader()->setCascadingSectionResizes(false);
        run_programmer_content->horizontalHeader()->setDefaultSectionSize(100);
        run_programmer_content->horizontalHeader()->setHighlightSections(true);
        run_programmer_content->horizontalHeader()->setMinimumSectionSize(0);
        run_programmer_content->horizontalHeader()->setProperty("showSortIndicator", QVariant(false));
        widget_3 = new QWidget(run_programmer_page);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        widget_3->setGeometry(QRect(660, 40, 91, 460));
        run_speed_set_button = new QPushButton(widget_3);
        run_speed_set_button->setObjectName(QString::fromUtf8("run_speed_set_button"));
        run_speed_set_button->setGeometry(QRect(8, 340, 80, 45));
        stop_programmer_button = new QPushButton(widget_3);
        stop_programmer_button->setObjectName(QString::fromUtf8("stop_programmer_button"));
        stop_programmer_button->setGeometry(QRect(8, 180, 80, 45));
        pause_programmer_button = new QPushButton(widget_3);
        pause_programmer_button->setObjectName(QString::fromUtf8("pause_programmer_button"));
        pause_programmer_button->setGeometry(QRect(8, 100, 80, 45));
        run_button = new QPushButton(widget_3);
        run_button->setObjectName(QString::fromUtf8("run_button"));
        run_button->setGeometry(QRect(8, 20, 80, 45));
        cycle_switch_button = new QPushButton(widget_3);
        cycle_switch_button->setObjectName(QString::fromUtf8("cycle_switch_button"));
        cycle_switch_button->setGeometry(QRect(8, 260, 80, 45));
        label = new QLabel(run_programmer_page);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(30, 20, 71, 17));
        run_position = new QTextEdit(run_programmer_page);
        run_position->setObjectName(QString::fromUtf8("run_position"));
        run_position->setGeometry(QRect(110, 13, 91, 31));
        run_position->setTextInteractionFlags(Qt::NoTextInteraction);
        main_interface->addWidget(run_programmer_page);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        main_interface->addWidget(page_3);
        widget_2 = new QWidget(centralwidget);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(0, 660, 741, 51));
        run_programmer = new QPushButton(widget_2);
        run_programmer->setObjectName(QString::fromUtf8("run_programmer"));
        run_programmer->setGeometry(QRect(650, 0, 90, 41));
        point_teacher = new QPushButton(widget_2);
        point_teacher->setObjectName(QString::fromUtf8("point_teacher"));
        point_teacher->setGeometry(QRect(240, 0, 90, 41));
        programmer_design = new QPushButton(widget_2);
        programmer_design->setObjectName(QString::fromUtf8("programmer_design"));
        programmer_design->setGeometry(QRect(450, 0, 90, 41));
        parameter_setting = new QPushButton(widget_2);
        parameter_setting->setObjectName(QString::fromUtf8("parameter_setting"));
        parameter_setting->setGeometry(QRect(20, 0, 90, 41));
        MainWindowDesign->setCentralWidget(centralwidget);

        retranslateUi(MainWindowDesign);
        QObject::connect(action_Quit, SIGNAL(triggered()), MainWindowDesign, SLOT(close()));

        main_interface->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindowDesign);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindowDesign)
    {
        MainWindowDesign->setWindowTitle(QApplication::translate("MainWindowDesign", "QTutorials", 0, QApplication::UnicodeUTF8));
        action_Quit->setText(QApplication::translate("MainWindowDesign", "&Quit", 0, QApplication::UnicodeUTF8));
        action_Quit->setShortcut(QApplication::translate("MainWindowDesign", "Ctrl+Q", 0, QApplication::UnicodeUTF8));
        action_Preferences->setText(QApplication::translate("MainWindowDesign", "&Preferences", 0, QApplication::UnicodeUTF8));
        actionAbout->setText(QApplication::translate("MainWindowDesign", "&About", 0, QApplication::UnicodeUTF8));
        actionAbout_Qt->setText(QApplication::translate("MainWindowDesign", "About &Qt", 0, QApplication::UnicodeUTF8));
        J5_name_2->setText(QApplication::translate("MainWindowDesign", "RY", 0, QApplication::UnicodeUTF8));
        J6_name_2->setText(QApplication::translate("MainWindowDesign", "RZ", 0, QApplication::UnicodeUTF8));
        J6_name->setText(QApplication::translate("MainWindowDesign", "J6", 0, QApplication::UnicodeUTF8));
        J3_name->setText(QApplication::translate("MainWindowDesign", "J3", 0, QApplication::UnicodeUTF8));
        J4_name_2->setText(QApplication::translate("MainWindowDesign", "RX", 0, QApplication::UnicodeUTF8));
        J4_name->setText(QApplication::translate("MainWindowDesign", "J4", 0, QApplication::UnicodeUTF8));
        J1_name->setText(QApplication::translate("MainWindowDesign", "J1", 0, QApplication::UnicodeUTF8));
        joint_coordinate_table->setText(QApplication::translate("MainWindowDesign", "\345\205\263\350\212\202\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8));
        J2_name->setText(QApplication::translate("MainWindowDesign", "J2", 0, QApplication::UnicodeUTF8));
        J2_name_2->setText(QApplication::translate("MainWindowDesign", "Y", 0, QApplication::UnicodeUTF8));
        J1_X->setText(QApplication::translate("MainWindowDesign", "X", 0, QApplication::UnicodeUTF8));
        Rectangular_coordinate_table->setText(QApplication::translate("MainWindowDesign", "\347\233\264\350\247\222\345\235\220\346\240\207\347\263\273", 0, QApplication::UnicodeUTF8));
        J3_name_2->setText(QApplication::translate("MainWindowDesign", "Z", 0, QApplication::UnicodeUTF8));
        J5_name->setText(QApplication::translate("MainWindowDesign", "J5", 0, QApplication::UnicodeUTF8));
        zero_setting->setText(QApplication::translate("MainWindowDesign", "\351\233\266\347\202\271\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        administrators_login->setText(QApplication::translate("MainWindowDesign", "\347\263\273\347\273\237\347\231\273\345\275\225", 0, QApplication::UnicodeUTF8));
        administrators_quit->setText(QApplication::translate("MainWindowDesign", "\347\263\273\347\273\237\351\200\200\345\207\272", 0, QApplication::UnicodeUTF8));
        administrators_modify_passwd->setText(QApplication::translate("MainWindowDesign", "\344\277\256\346\224\271\345\257\206\347\240\201", 0, QApplication::UnicodeUTF8));
        user_login->setText(QApplication::translate("MainWindowDesign", "\346\223\215\344\275\234\345\221\230\347\231\273\345\275\225", 0, QApplication::UnicodeUTF8));
        user_quit->setText(QApplication::translate("MainWindowDesign", "\346\223\215\344\275\234\345\221\230\351\200\200\345\207\272", 0, QApplication::UnicodeUTF8));
        user_modify_passwd->setText(QApplication::translate("MainWindowDesign", "\344\277\256\346\224\271\345\257\206\347\240\201", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindowDesign", "\347\263\273\347\273\237\347\231\273\345\275\225\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindowDesign", "\346\223\215\344\275\234\345\221\230\347\231\273\345\275\225\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        joint_coorinate_button->setText(QApplication::translate("MainWindowDesign", "\345\205\263\350\212\202\345\235\220\346\240\207", 0, QApplication::UnicodeUTF8));
        world_coorinate_button->setText(QApplication::translate("MainWindowDesign", "\344\270\226\347\225\214\345\235\220\346\240\207", 0, QApplication::UnicodeUTF8));
        tool_coorinate_button->setText(QApplication::translate("MainWindowDesign", "\345\267\245\345\205\267\345\235\220\346\240\207", 0, QApplication::UnicodeUTF8));
        workpiece_coordinate_button->setText(QApplication::translate("MainWindowDesign", "\345\267\245\344\273\266\345\235\220\346\240\207", 0, QApplication::UnicodeUTF8));
        J1_negative_direction->setText(QApplication::translate("MainWindowDesign", "+", 0, QApplication::UnicodeUTF8));
        J3_teacher_label->setText(QApplication::translate("MainWindowDesign", "J3", 0, QApplication::UnicodeUTF8));
        J2_teach_label->setText(QApplication::translate("MainWindowDesign", "J2", 0, QApplication::UnicodeUTF8));
        J1_teach_label->setText(QApplication::translate("MainWindowDesign", "J1", 0, QApplication::UnicodeUTF8));
        J5_teach_label->setText(QApplication::translate("MainWindowDesign", "J5", 0, QApplication::UnicodeUTF8));
        J4_teach_label->setText(QApplication::translate("MainWindowDesign", "J4", 0, QApplication::UnicodeUTF8));
        J6_teach_label->setText(QApplication::translate("MainWindowDesign", "J6", 0, QApplication::UnicodeUTF8));
        J1_positive_direction->setText(QApplication::translate("MainWindowDesign", "-", 0, QApplication::UnicodeUTF8));
        J2_positive_direction->setText(QApplication::translate("MainWindowDesign", "-", 0, QApplication::UnicodeUTF8));
        J2_negative_direction->setText(QApplication::translate("MainWindowDesign", "+", 0, QApplication::UnicodeUTF8));
        J3_positive_direction->setText(QApplication::translate("MainWindowDesign", "-", 0, QApplication::UnicodeUTF8));
        J4_positive_direction->setText(QApplication::translate("MainWindowDesign", "-", 0, QApplication::UnicodeUTF8));
        J5_positive_direction->setText(QApplication::translate("MainWindowDesign", "-", 0, QApplication::UnicodeUTF8));
        J6_positive_direction->setText(QApplication::translate("MainWindowDesign", "-", 0, QApplication::UnicodeUTF8));
        J3_negative_direction->setText(QApplication::translate("MainWindowDesign", "+", 0, QApplication::UnicodeUTF8));
        J4_negative_direction->setText(QApplication::translate("MainWindowDesign", "+", 0, QApplication::UnicodeUTF8));
        J5_negative_direction->setText(QApplication::translate("MainWindowDesign", "+", 0, QApplication::UnicodeUTF8));
        J6_negative_direction->setText(QApplication::translate("MainWindowDesign", "+", 0, QApplication::UnicodeUTF8));
        new_point->setText(QApplication::translate("MainWindowDesign", " \346\226\260\345\273\272", 0, QApplication::UnicodeUTF8));
        modify_point->setText(QApplication::translate("MainWindowDesign", "\344\277\256\346\224\271", 0, QApplication::UnicodeUTF8));
        delete_point->setText(QApplication::translate("MainWindowDesign", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
        save_point->setText(QApplication::translate("MainWindowDesign", "\344\277\235\345\255\230", 0, QApplication::UnicodeUTF8));
        stop_point_motion->setText(QApplication::translate("MainWindowDesign", "\345\201\234\346\255\242", 0, QApplication::UnicodeUTF8));
        point_to_point_motion->setText(QApplication::translate("MainWindowDesign", "\347\202\271\345\257\271\347\202\271", 0, QApplication::UnicodeUTF8));
        straight_line_motion->setText(QApplication::translate("MainWindowDesign", "\347\233\264\347\272\277", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindowDesign", "\351\200\237\345\272\246\357\274\232", 0, QApplication::UnicodeUTF8));
        insert_button->setText(QApplication::translate("MainWindowDesign", "\346\217\222\345\205\245", 0, QApplication::UnicodeUTF8));
        delete_button->setText(QApplication::translate("MainWindowDesign", "\345\210\240\351\231\244", 0, QApplication::UnicodeUTF8));
        save_button->setText(QApplication::translate("MainWindowDesign", "\344\277\235\345\255\230", 0, QApplication::UnicodeUTF8));
        save_as_button->setText(QApplication::translate("MainWindowDesign", "\345\217\246\345\255\230", 0, QApplication::UnicodeUTF8));
        new_file_button->setText(QApplication::translate("MainWindowDesign", "\346\226\260\345\273\272", 0, QApplication::UnicodeUTF8));
        open_button->setText(QApplication::translate("MainWindowDesign", "\346\211\223\345\274\200", 0, QApplication::UnicodeUTF8));
        common_function_instruction->setText(QApplication::translate("MainWindowDesign", "\345\270\270\347\224\250\345\212\237\350\203\275\346\214\207\344\273\244", 0, QApplication::UnicodeUTF8));
        sport_control_instruction->setText(QApplication::translate("MainWindowDesign", "\350\277\220\345\212\250\346\216\247\345\210\266\346\214\207\344\273\244", 0, QApplication::UnicodeUTF8));
        extended_instruction->setText(QApplication::translate("MainWindowDesign", "\346\211\251\345\261\225\346\214\207\344\273\244", 0, QApplication::UnicodeUTF8));
        run_speed_set_button->setText(QApplication::translate("MainWindowDesign", "\350\277\220\350\241\214\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        stop_programmer_button->setText(QApplication::translate("MainWindowDesign", "\345\201\234\346\255\242\347\250\213\345\272\217", 0, QApplication::UnicodeUTF8));
        pause_programmer_button->setText(QApplication::translate("MainWindowDesign", "\346\232\202\345\201\234\347\250\213\345\272\217", 0, QApplication::UnicodeUTF8));
        run_button->setText(QApplication::translate("MainWindowDesign", "\350\277\220\350\241\214", 0, QApplication::UnicodeUTF8));
        cycle_switch_button->setText(QApplication::translate("MainWindowDesign", "\345\221\250\346\234\237\345\274\200\345\205\263", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindowDesign", "\350\277\220\350\241\214\344\275\215\347\275\256\357\274\232", 0, QApplication::UnicodeUTF8));
        run_programmer->setText(QApplication::translate("MainWindowDesign", "\350\277\220\350\241\214\347\250\213\345\272\217", 0, QApplication::UnicodeUTF8));
        point_teacher->setText(QApplication::translate("MainWindowDesign", "\347\202\271\344\275\215\346\225\231\345\257\274", 0, QApplication::UnicodeUTF8));
        programmer_design->setText(QApplication::translate("MainWindowDesign", "\347\250\213\345\272\217\350\256\276\350\256\241", 0, QApplication::UnicodeUTF8));
        parameter_setting->setText(QApplication::translate("MainWindowDesign", "\345\217\202\346\225\260\350\256\276\345\256\232", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindowDesign: public Ui_MainWindowDesign {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAIN_WINDOW_H
